# Generated by Django 6.0.3 on 2026-03-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_rename_bio_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
