# Generated by Django 6.0.3 on 2026-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
