# Generated by Django 6.0.3 on 2026-03-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_offers_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='delivery_time',
            new_name='min_delivery_time',
        ),
    ]
