# Generated by Django 6.0.3 on 2026-03-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_alter_offerdetail_price_alter_offers_price'),
        ('users_app', '0004_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='users_app.userprofile'),
        ),
    ]
