# Generated by Django 6.0.3 on 2026-03-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_alter_offers_business_alter_orders_user'),
        ('users_app', '0004_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='business',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to='users_app.userprofile'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='users_app.userprofile'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='offer_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='revisions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
