# Generated by Django 6.0.3 on 2026-03-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_rename_order_date_orders_created_at_and_more'),
        ('users_app', '0004_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='business',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='users_app.userprofile'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='users_app.userprofile'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
